znbpost/urls.py
from django.urls import path, re_path

from . import views

app_name = 'znbpost'
urlpatterns = [
    path('', views.article_index, name='article_index'),
    # path('<slug:slug>/', views.article_detail, name='article_detail'),
    re_path(r'^articles/(?P<slug>[\w-]+)/$', views.article_detail, name='article_detail'),
    re_path(r'^articles/(?P<slug>[\w-]+)/vote/$', views.article_vote, name='article_vote'),
    re_path(r'^articles/(?P<slug>[\w-]+)/results/$', views.article_results, name='article_results'),
    re_path(r'^p/(?P<slug>[\w-]+)/$', views.page_detail, name='page_detail'),
]

# TODO convert old-style URLConf
# urlpatterns = [
#     url(r'^$', views.HomeList.as_view(), name='index'),
#     url(r'^feed/$', LatestArticlesFeed(), name='feed'),
#     url(r'^my-account/$', views.AccountHome.as_view(), name='account_home'),
#     url(r'^app-check/$', views.appcheck, name='appcheck'),
#     url(r'^contact/$', views.ContactPage.as_view(), name='contact'),
#     url(r'^articles/$', views.ArticleList.as_view(), name='article_list'),
#     url(r'^category/(?P<slug>[-\w]+)/$', views.ArticleCategoryList.as_view(), name='category'),
#     url(r'^work/$', views.PageDetail.as_view(), {'slug': 'work'}, name='page_detail'),
#     url(r'^p/(?P<slug>[-\w]+)/$', views.PageDetail.as_view(), name='page_detail'),
#     url(r'^(?P<slug>[-\w]+)/$', views.ArticleDetail.as_view(), name='article_detail'),
#     url(r'^download$', views.download, name='download'), # TODO move to its own app, see views
# ]

znbpost/templates/znbpost/article_detail.html
{% extends "znbpost/base.html" %}

{% block title %}{{ article.title }} - {{ block.super }}{% endblock %}

{% block content %}
  <p>ID: {{ article.id }}<p>
  <p>Title: {{ article.title }}<p>
    
  {% if article.categories.all %}
    <p>Categories this article belongs to</p>
    <ul>
    {% for category in article.categories.all %}
      <li>{{ category.title }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  
  <form action="{% url 'znbpost:article_vote' slug=article.slug %}" method="post">
    {% csrf_token %}
    <p>Ranking for this article</p>
    {% for r in ranking %}
        <input type="radio" name="ranking" id="ranking-{{ forloop.counter }}" value="{{ r }}">
        <label for="ranking-{{ forloop.counter }}">{{ r }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
  </form>
  
  <p><a href="{% url 'znbpost:article_index' %}">Back home</a></p>
  
  <p>Permalink: {{ article.get_absolute_url }} </p>
  
  <figure>
    <img src="{{ article.image.url }}" alt="" title="" />
    <figcaption>{{ article.image_credit_html|safe }}</figcaption>
  <figure/>
    
{% endblock content %}

znbpost/templates/znbpost/article_index.html
{% extends "znbpost/base.html" %}

{% block title %}Latest Articles - {{ block.super }}{% endblock %}

{% block content %}
  <h1>index.html znbpost</h1>
  
  {% if latest_articles %}
    <ul>
    {% for article in latest_articles %}
        <li><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
    {% endfor %}
    </ul>
  {% else %}
      <p>No articles available.</p>
  {% endif %}

{% endblock content %}

znbpost/templates/znbpost/article_results.html
{% extends "znbpost/base.html" %}

{% block title %}{{ article.title }} - {{ block.super }}{% endblock %}

{% block content %}
  <h2>Results after voting to rank article</h2>
  <p>ID: {{ article.id }}<p>
  <p>Title: {{ article.title }}<p>
  <p><a href="{% url 'znbpost:article_index' %}">Back home</a></p>
{% endblock content %}

znbpost/templates/znbpost/base.html
{% extends "base.html" %}

{% block bodyclass %}{{block.super}} base-znbpost{% endblock bodyclass %}

znbpost/templates/znbpost/index.html
{% extends "znbpost/base.html" %}

{% block content %}
  <h1>index.html znbpost</h1>
{% endblock content %}

znbpost/templates/znbpost/page_detail.html
{% extends "znbpost/base.html" %}

{% block title %}{{ page.title }} - {{ block.super }}{% endblock %}

{% block content %}
  <p>ID: {{ page.id }}<p>
  <p>Title: {{ page.title }}<p>
  
  {% if page.categories.all %}
    <p>Categories this page belongs to</p>
    <ul>
    {% for category in page.categories.all %}
      <li>{{ category.title }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  
  <p><a href="{% url 'znbpost:article_index' %}">Back home</a></p>
  
  <p>Permalink: {{ page.get_absolute_url }} </p>
  
{% endblock content %}